version: '3.1'

services:
  hope-aqi-archiver:
    image: hellej/hope-aqi-archiver:latest
    secrets:
     - ENFUSER_S3_ACCESS_KEY_ID
     - ENFUSER_S3_SECRET_ACCESS_KEY
     - HOPE_CSC_S3_ACCESS_KEY_ID
     - HOPE_CSC_S3_SECRET_ACCESS_KEY

secrets:
  ENFUSER_S3_ACCESS_KEY_ID:
    external: true
  ENFUSER_S3_SECRET_ACCESS_KEY:
    external: true
  HOPE_CSC_S3_ACCESS_KEY_ID:
    external: true
  HOPE_CSC_S3_SECRET_ACCESS_KEY:
    external: true
