version: '3.1'

services:
  hope-aqi-archiver:
    image: hellej/hope-aqi-archiver:latest
    environment:
     - HOPE_CSC_S3_ADDRESS=https://a3s.fi
     - HISTORY_IMPORT_ENABLED=True
     - HISTORY_IMPORT_FROM_TIME=2020-02-09T09
    secrets:
     - ENFUSER_S3_ACCESS_KEY_ID
     - ENFUSER_S3_SECRET_ACCESS_KEY
     - HOPE_CSC_S3_ACCESS_KEY_ID
     - HOPE_CSC_S3_SECRET_ACCESS_KEY

secrets:
  ENFUSER_S3_ACCESS_KEY_ID:
    external: true
  ENFUSER_S3_SECRET_ACCESS_KEY:
    external: true
  HOPE_CSC_S3_ACCESS_KEY_ID:
    external: true
  HOPE_CSC_S3_SECRET_ACCESS_KEY:
    external: true
